### ISSUE TITLE
Error: Secure Message failed to verify signature: failure

### ISSUE THREAD

**Issue by davidkhala** [5sWind/nodejs-crypto-lab#2]
OS: MacOS
nodejs: v8.16.0
```
mediconcens-Mac-mini:nodejs-crypto-lab mediconcen$ node --experimental-modules interative_mode.mjs abc
(node:12167) ExperimentalWarning: The ESM module loader is experimental.
==== Generating keypairs. ====
Generated Private Key:  { privateKey: 'UkVDMgAAAC3jwWKSAPuNxS3Ht9fa1lYFGnYcceFffWOP2jfNCnJK6Ek94NMP' }
Generated Public Key:  { publicKey: 'VUVDMgAAAC2bCB+9App8SvZtRCjnB/i70iJ7mJEXLhCvy22xqMb1L1duQ4NY' }
==== Encrypting Message. ====
Successfully encrypted message:  { encryptedMessage: 'ICcEJjcAAAAAAQFADAAAABAAAAADAAAAiImU0YZycBemPjZFNFSG836qPpS9JqZT2+Arp0DFwA==' }
==== Decrypting Message. ====
Successfully decrypted message:  { decryptedMessage: 'abc' }
==== Signing Message. ====
Successfully signed message:  { signedMessage: 'ICYEJgMAAABIAAAAYWJjMEYCIQCnmQUGNnoZrfmD3Z9apThlk3KdjvD/XEBJRQFhZBj09gIhALl+AVrgKZs6wEhnYSjH/WHasKuxK4lh7NzztUsVUwgB' }
==== Verifying Message. ====
ERROR:  { Error: Secure Message failed to verify signature: failure
    at verifyMessage (file:///Users/mediconcen/Documents/nodejs-crypto-lab/utils/message_verify.mjs:6:26)
    at file:///Users/mediconcen/Documents/nodejs-crypto-lab/interative_mode.mjs:26:23
    at ModuleJob.run (internal/loader/ModuleJob.js:97:14)
    at <anonymous> code: 11 }
Successfully verified message:  { verifiedMessage: undefined }
```

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
Hi, I have the same issue.
I had a look at Themis source code verify function previously, but did not see any difference in other function codes and my implement function code. And I found there are no examples or docs regarding on this.
I suppose this is the Themis js library issue or environment issue in current.
Later I will open an issue in Themis repo.
Thanks!

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
https://github.com/cossacklabs/themis/issues/464.

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
@davidkhala I have submitted a new patch https://github.com/5sWind/nodejs-crypto-lab/commit/413dfb90684b8935b3b3e8a423368d903981f970. It works (I forget to add a receiving object as I returned two fields: private key and public key).

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
A follow-up story: the new version of jsthemis v0.11.2 has improved the log message of sign/verify mode in SecureMessage for avoiding misuse. See https://github.com/cossacklabs/themis/issues/464.

**Comment by davidkhala** [comment]
Cool, your new version passes all tests
